### ISSUE TITLE
addSchema erroe

### ISSUE THREAD

**Issue by unagi2020** [TomDoesTech/fastify-prisma-rest-api#2]
I am getting  TypeError: schema_1.default is not iterable error during schema addition.

for (const schema of [...productSchemas]) {
  server.addSchema(schema);
}

Being a newbie not sure how to default export the schema file. Please help. I am doing something stupidly wrong.

**Comment by unagi2020** [comment]
Please delete this issue. My bad was not following instructions.

**Comment by tomanagle** [comment]
> Please delete this issue. My bad was not following instructions.

All good :)

**Comment by hilmanski** [comment]
can you clarify what's the problem here ? having a same problem.

when trying console log `userSchemas` it shows undefined

**Comment by hilmanski** [comment]
I got it it caused by my different structure running the function
```

// Need to loop this outside funciton
for (const schema of userSchemas) {
  server.addSchema(schema);
}

const start = async () => {
  const PORT = 3001;
  const HOST = '0.0.0.0';

  // Register grouped routes
  server.register(userRoutes, { prefix: "v1/users" });

  // Running Server
  try {
    await server.listen({ port: PORT, host: HOST })
  } catch (err) {
    server.log.error(err)
    process.exit(1)
  }
}
start()
```
